#!/bin/bash
AZ=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
REGION="`echo \"$AZ\" | sed 's/[a-z]$//'`"
DOMAIN="$REGION.compute.amazonaws.com"
HOSTNAME=$(curl -s http://169.254.169.254/latest/meta-data/public-hostname | cut -d . -f 1)
LOCAL_IPV4=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
hostname $HOSTNAME
echo $HOSTNAME > /etc/hostname
cat<<EOF > /etc/hosts
# This file is automatically generated by ec2-hostname script
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
$LOCAL_IPV4 $HOSTNAME.$DOMAIN $HOSTNAME
EOF
echo DOMAIN=$DOMAIN >> /etc/sysconfig/network
echo SEARCH=$REGION.compute.amazonaws.com >> /etc/sysconfig/network
systemctl restart network